/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify the credentials and set the session cookie. 401 on any mismatch.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie. Always succeeds, authenticated or not.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The current user, for the UI to render the session state.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password after re-checking the current one. 403 if it is wrong.
         */
        post: operations["change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Checks
         * @description The full check catalogue — the same list as ``webvigil list-checks``, with metadata.
         */
        get: operations["list_checks_api_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Defaults
         * @description The default scan options, so the UI's new-scan form can pre-fill sensible values.
         */
        get: operations["config_defaults_api_config_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe and tool version. The only unauthenticated endpoint besides setup.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description Newest scans first, optionally filtered by ``status``, cursor-paginated by ``limit``.
         */
        get: operations["list_scans_api_scans_get"];
        put?: never;
        /**
         * Create Scan
         * @description Queue a scan and wake the runner. Returns the new scan row (status ``queued``).
         */
        post: operations["create_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description One scan's full detail — metadata, options, and the detected-technology inventory.
         */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Scan
         * @description Delete a finished scan and its findings (cascade). 409 if it is still active.
         */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Scan
         * @description Cancel a running or queued scan. 409 if it is already finished or not cancellable.
         */
        post: operations["cancel_scan_api_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description A scan's findings, optionally filtered by ``check_id`` or a minimum ``severity``,
         *     sorted severity-descending then check id / URL / sub-location.
         */
        get: operations["list_findings_api_scans__scan_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Report
         * @description Render a finished scan into ``json`` / ``sarif`` / ``html`` / ``md`` from the stored
         *     rows. ``download=false`` serves it inline. 409 when the scan has no results.
         */
        get: operations["download_report_api_scans__scan_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Status
         * @description Whether first-run setup is still needed. Unauthenticated — the UI checks it on load.
         */
        get: operations["setup_status_api_setup_get"];
        put?: never;
        /**
         * Create First User
         * @description Create the single account. Unauthenticated, but 409s once an account exists.
         */
        post: operations["create_first_user_api_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckOut
         * @description One registered check, for the check-catalogue endpoint.
         */
        CheckOut: {
            /** Category */
            category: string;
            /** Cwe */
            cwe: number[];
            /** Default Severity */
            default_severity: string;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            /** References */
            references: string[];
        };
        /**
         * EvidenceOut
         * @description One labelled evidence snippet.
         */
        EvidenceOut: {
            /** Content */
            content: string;
            /** Label */
            label: string;
        };
        /** @enum {string} */
        FailOn: "none" | "info" | "low" | "medium" | "high" | "critical";
        /**
         * FindingOut
         * @description One finding in a scan-detail response; severity and confidence as names, not ints.
         */
        FindingOut: {
            /** Check Id */
            check_id: string;
            /** Confidence */
            confidence: string;
            /** Cwe */
            cwe: number[];
            /** Description */
            description: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Fingerprint */
            fingerprint: string;
            location: components["schemas"]["LocationOut"];
            /** References */
            references: string[];
            /** Remediation */
            remediation: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description The health endpoint's payload: liveness and the tool version.
         */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LocationOut
         * @description A finding's location in a response.
         */
        LocationOut: {
            /** Cookie */
            cookie?: string | null;
            /** Header */
            header?: string | null;
            /**
             * Method
             * @default GET
             */
            method: string;
            /** Param */
            param?: string | null;
            /** Url */
            url: string;
        };
        /**
         * LoginIn
         * @description Login body.
         */
        LoginIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** Page[ScanSummary] */
        Page_ScanSummary_: {
            /** Items */
            items: components["schemas"]["ScanSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * PasswordChangeIn
         * @description Password-change body: the current password plus the new one.
         */
        PasswordChangeIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ScanCreate
         * @description New-scan request body.
         *
         *     Attributes:
         *         target (str): The URL to scan; validated with
         *             :meth:`~webvigil.core.target.Target.parse`.
         *         mode (ScanMode): Passive (default) or Active.
         *         scope (Scope): Crawl breadth. Defaults to
         *             :attr:`~webvigil.core.target.Scope.HOST`.
         *         max_pages (int | None): Crawler page cap; must be > 0 when given.
         *         delay_ms (int | None): Delay between requests; must be >= 0 when given.
         *         follow_robots (bool | None): Honour ``robots.txt``.
         *         authorized_by (str | None): Required for an Active scan.
         *         fail_on (FailOn | None): Recorded on the scan for later report exit
         *             codes.
         *         disabled_checks (list[str]): Check ids to skip. Defaults to empty.
         */
        ScanCreate: {
            /** Authorized By */
            authorized_by?: string | null;
            /** Delay Ms */
            delay_ms?: number | null;
            /**
             * Disabled Checks
             * @default []
             */
            disabled_checks: string[];
            fail_on?: components["schemas"]["FailOn"] | null;
            /** Follow Robots */
            follow_robots?: boolean | null;
            /** Max Pages */
            max_pages?: number | null;
            /** @default passive */
            mode: components["schemas"]["ScanMode"];
            /** @default host */
            scope: components["schemas"]["Scope"];
            /** Target */
            target: string;
        };
        /**
         * ScanDefaults
         * @description The default scan options, so the UI's new-scan form can pre-fill them.
         */
        ScanDefaults: {
            /** Delay Ms */
            delay_ms: number;
            /** Fail On */
            fail_on: string;
            /** Follow Robots */
            follow_robots: boolean;
            /** Max Pages */
            max_pages: number;
            /** Mode */
            mode: string;
            /** Scope */
            scope: string;
        };
        /**
         * ScanMode
         * @description Safe Mode (default) versus opt-in Active Mode.
         *
         *     Attributes:
         *         PASSIVE (str): Observation only — safe to point at production.
         *         ACTIVE (str): Sends crafted requests; requires an authorization.
         * @enum {string}
         */
        ScanMode: "passive" | "active";
        /**
         * ScanOut
         * @description The full scan-detail response: everything in :class:`ScanSummary` plus the extras.
         *
         *     Attributes:
         *         authorized_by (str | None): Active-Mode attestation.
         *         tool_version (str | None): WebVigil version that ran the scan.
         *         error (str | None): Failure message, when applicable.
         *         pages_scanned (int): Pages the crawler fetched.
         *         options (dict[str, Any]): The request's extra options.
         *         technologies (list[TechnologyOut]): The detected-technology inventory.
         */
        ScanOut: {
            /** Authorized By */
            authorized_by: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Mode */
            mode: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Pages Scanned */
            pages_scanned: number;
            /** Scope */
            scope: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Target */
            target: string;
            /** Technologies */
            technologies: components["schemas"]["TechnologyOut"][];
            /** Tool Version */
            tool_version: string | null;
        };
        /**
         * ScanStatus
         * @description Lifecycle state of a stored scan.
         *
         *     Attributes:
         *         QUEUED (str): Waiting for the runner's execution slot.
         *         RUNNING (str): Currently executing.
         *         COMPLETED (str): Finished; findings are stored.
         *         FAILED (str): Ended with a controlled engine error or a crash.
         *         CANCELLED (str): Cancelled by the user.
         *         INTERRUPTED (str): Left ``RUNNING`` by a process that died; recovered on
         *             the next startup.
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
        /**
         * ScanSummary
         * @description A scan as it appears in the list endpoint — identity, status, severity counts.
         */
        ScanSummary: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Mode */
            mode: string;
            /** Scope */
            scope: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Target */
            target: string;
        };
        /**
         * Scope
         * @description How wide the scan is allowed to reach.
         *
         *     Attributes:
         *         HOST (str): Only the exact target host.
         *         SUBDOMAINS (str): The target's registrable domain and any subdomain.
         * @enum {string}
         */
        Scope: "host" | "subdomains";
        /**
         * SetupIn
         * @description First-run setup body: the credentials for the single account.
         */
        SetupIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * TechnologyOut
         * @description One detected client-side library (spec 004, RF-17). Detail payload only.
         *
         *     Attributes:
         *         name (str): Library name.
         *         version (str | None): Detected version, or ``None``.
         *         detection (str): How it was found (the ``DetectionMethod`` value).
         *         source_url (str): URL the detection came from.
         *         vulnerable (bool): Whether an advisory matched.
         *         advisories (list[str]): Matching advisory identifiers.
         */
        TechnologyOut: {
            /** Advisories */
            advisories: string[];
            /** Detection */
            detection: string;
            /** Name */
            name: string;
            /** Source Url */
            source_url: string;
            /** Version */
            version: string | null;
            /** Vulnerable */
            vulnerable: boolean;
        };
        /**
         * UserOut
         * @description The current user, as returned by the auth endpoints.
         */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_checks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOut"][];
                };
            };
        };
    };
    config_defaults_api_config_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDefaults"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_scans_api_scans_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ScanStatus"] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ScanSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_scans__scan_id__findings_get: {
        parameters: {
            query?: {
                severity?: string | null;
                check_id?: string | null;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_scans__scan_id__report_get: {
        parameters: {
            query?: {
                format?: string;
                download?: boolean;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    create_first_user_api_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
