/**
 * @file ESLint flat config for the web UI.
 *
 * Next 15 still ships its rules as legacy `extends` presets, so `FlatCompat`
 * translates them into the flat-config array. `"prettier"` comes last on
 * purpose: it switches off every stylistic rule that would otherwise fight the
 * formatter. The `ignores` block covers generated and tool-owned paths and
 * tracks `.prettierignore`.
 */

import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

// Flat config runs as ESM, which has no `__dirname`; rebuild it from the module
// URL so FlatCompat can resolve the presets relative to this file.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      ".playwright-tmp/**",
      "src/lib/api-types.ts", // generated by `pnpm gen:api`
      "next-env.d.ts", // generated by Next
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),
];

export default eslintConfig;
