/**
 * @file ESLint flat config for the web UI.
 *
 * `eslint-config-next` 16 ships a native flat config, so the old `FlatCompat`
 * shim is gone. Its `core-web-vitals` array already bundles the TypeScript
 * rules. `prettier` comes last on purpose: it switches off every stylistic
 * rule that would otherwise fight the formatter. The `ignores` block covers
 * generated and tool-owned paths and tracks `.prettierignore`.
 */

import next from "eslint-config-next/core-web-vitals";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      ".playwright-tmp/**",
      "src/lib/api-types.ts", // generated by `pnpm gen:api`
      "next-env.d.ts", // generated by Next
    ],
  },
  ...next,
  prettier,
];

export default eslintConfig;
